mysite/food/urls.py
from django.urls import path, include
from food import views

app_name = 'food'

urlpatterns = [


    # function based index view
    # ----------------------------------------------------
    path('home/', views.index, name = 'index'),

    # class based index view
    # ----------------------------------------------------
    #path('home', views.IndexClassView.as_view(), name = 'index'),

    # function based detail view
    # ----------------------------------------------------
    path('detail/<int:item_id>/', views.detail, name = 'detail'),

    # class based detail view
    # ----------------------------------------------------
    # path('detail/<int:pk>/', views.FoodDetail.as_view(), name = 'detail'),


    # function based create item view
    # ----------------------------------------------------
    # path('add/', views.create_item, name='create_item'),

    # class based create item view
    # ----------------------------------------------------
    path('add/', views.CreateItem.as_view(), name='create_item'),


    #function based update item view
    # ----------------------------------------------------
    path('update/<int:id>/', views.update_item, name='update_item'),

    # function based delete item view
    # ----------------------------------------------------
    path('delete/<int:id>/', views.delete_item, name='delete_item'),


]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as users_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('users/', include('users.urls')),
    path('register/', users_views.register, name='register'),
    path('login/', users_views.login_view, name='login'),
    path('logout/', users_views.logout_view, name='logout'),
    path('profile/', users_views.profilepage, name='profile'),
]

urlpatterns += [] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from users import views
from django.urls import path

app_name = 'users'
urlpatterns = [
    
    # orders
    path('orders/<int:id>/<int:pdcd>/<str:user>/', views.Orders, name='orders'),

    # updating customer orders
    path('upd_orders/<int:id>/<int:upd_order_id>/', views.update_orders, name="upd_orders"),

    # customer rating-feedback view
    path('crf/<int:it_id>/<int:pc>/', views.CusRatFeed, name='CusRatFeed'),

    # updating customer rating-feedback
    path('crf_upd/<int:details_id>/<int:crf_id>/', views.update_crf, name='upd_crf'),

    # deleting customer rating-feedback
    path('del_crf/<int:details_id>/<int:crf_id>/', views.delete_crf, name='del_crf'),

    # paypal checkout button
    path('buy/<int:amt>/<int:qnt>/', views.Payment, name='buy'),

    # paypal on approve
    path('oa/', views.OnApprove, name='oa'),

    # paypal payment success
    path('ps/', views.PaymentSuccess, name='ps'),


]

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image =  models.ImageField(default='profilepic.jpg', upload_to = 'profile_pictures')
    location = models.CharField(max_length=100)
    user_type = models.CharField(max_length=200, default='users')

    def __str__(self):
        return self.user.username
    

class CusOrders(models.Model):

    order_id  = models.AutoField(primary_key=True)
    prod_code = models.IntegerField()
    quantity  = models.IntegerField(default=1)
    user      = models.CharField(max_length=200)

    def __str__(self):
        return str(
            (
                str(self.order_id),
                str(self.prod_code),
                str(self.quantity),
                str(self.user)
            )
        )
    

class CusRatingFeedback(models.Model):
    prod_code = models.IntegerField(default=1)
    ratings = models.FloatField()
    feedback = models.CharField(max_length=200)
    username  = models.CharField(max_length=200, default='username')
    user_type = models.CharField(max_length=200, default='Cust')

    def __str__(self):
        return str(
            (
                str(self.prod_code),
                str(self.ratings),
                str(self.feedback),
                str(self.username),
                str(self.user_type)
            )
        )

mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from users.models import CusOrders, CusRatingFeedback

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    class Meta:
        model = User
        fields = ['username','first_name', 'last_name', 'email','password1', 'password2']


class CusOrdersUpd(forms.ModelForm):
    
    class Meta:
        model = CusOrders
        fields = ['quantity']

class CusRatFeedForm(forms.ModelForm):

    class Meta:
        model = CusRatingFeedback
        fields = ['ratings','feedback']

mysite/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from users.forms import RegisterForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from users.models import CusOrders, CusRatingFeedback
from users.forms import CusOrdersUpd, CusRatFeedForm
from django.http import JsonResponse
import json

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            messages.success(request, 'Welcome {}, your account has been successfully created. Now you may log in'.format(username))
            form.save()
            return redirect('login')
    
    else:
        form = RegisterForm()

        context = {
            'form': form
        }

        return render(request, 'users/register.html', context)


def login_view(request):
     
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        
        if user is None:
            messages.success(
                request,'Invalid Login, Try Again')
            return redirect('login')
    
        elif user.is_superuser:
            login(request, user)
            messages.success(
                request,'Welcome SuperUser  {}, you have been successfully logged in'.format(request.user.username))
            return redirect('food:index')
        
        elif user is not None:
            login(request, user)
            messages.success(
                request,'Welcome {}, you have been successfully logged in'.format(request.user.username))
            return redirect('food:index')
        
    context = {
                         
    }
        
    return render(request, 'users/login.html', context)

def logout_view(request):
    
    messages.warning(
                request,'{}, you have been successfully logged out'.format(request.user.username))
    logout(request)
    return redirect('food:index')

@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

def Orders(request, id, pdcd, user):

    context = {
        'pdcd': pdcd,
        'user': user
    }

    if request.method == 'POST':

        Obj_CusOrds = CusOrders(
            prod_code=pdcd,
            user=user,
            quantity=request.POST.get('qty')
        )

        Obj_CusOrds.save()

        return redirect('food:detail', item_id=id)
        

    return render(request, 'users/orders.html', context)


def update_orders(request, id, upd_order_id):

    coo = CusOrders.objects.get(order_id=upd_order_id)
    form = CusOrdersUpd(request.POST or None, instance=coo)

    context = {
        'form': form  
    }

    if form.is_valid():
        form.save()
        return redirect('food:detail', item_id=id)

    return render(request, 'users/orders_upd.html', context)

def CusRatFeed(request, it_id, pc):

    form = CusRatFeedForm(request.POST or None)

    context ={
        'form': form
    }

    if request.method == 'POST':
        form.instance.prod_code = pc
        form.instance.username = request.user.username
        form.save()
        return redirect('food:detail', item_id=it_id)
    
    return render(request, 'users/item-form.html', context)

def update_crf(request, details_id, crf_id):

    crfo = CusRatingFeedback.objects.get(pk=crf_id)
    form = CusRatFeedForm(request.POST or None, instance=crfo)

    context = {
        'form': form
    }

    if form.is_valid():
        form.save()
        return redirect('food:detail', item_id=details_id)

    return render(request, 'users/crf_upd.html', context)

def delete_crf(request, details_id, crf_id):
    
     crfo = CusRatingFeedback.objects.get(pk=crf_id)

     context = {
         'crfo': crfo
     }

     if request.method == 'POST':
         crfo.delete()
         return redirect('food:detail', item_id=details_id)

     return render(request, 'users/crf_del.html', context)

def Payment(request, amt, qnt):

    context = {
        'amt':amt,
        'qnt':qnt,
        'tot':amt * qnt
    }

    return render(request, 'users/payment.html', context)


def OnApprove(request):

    if request.method == 'POST':
        body = json.loads(request.body)
        print(body)

        context = {

        }

        return JsonResponse(context)


def PaymentSuccess(request):

    return render(request, 'users/pymtsuccess.html')

mysite/users/templates/users/crf_del.html
{% extends 'food/base.html' %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete</p>
    {{ crfo.prod_code }}
    {{ crfo.ratings }}
    {{ crfo.feedback }}
    <button type="delete">Confirm</button>
</form>
{% endblock  %}

mysite/users/templates/users/crf_upd.html
{% extends "food/base.html" %} 

{% block body %}

<form method="POST">
    {% csrf_token %}
    {{ form }}
<button type="submit" class="btn btn-success btn-sm">Save</button>
</form>


{% endblock  %}

mysite/users/templates/users/item-form.html
<form action="" method="POST">
    {% csrf_token %}
    {{ form}}
<button type="submit" class="btn btn-success btn-sm">Save</button>
</form>

mysite/users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}

<br><br><br>

<div class="container">
    <div class="row">
         <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                    
                        <label class="offset-md-1" for="user">Username:</label><br>
                        <input class="offset-md-1" id="user" name="username"><br>
                    
                        <label class="offset-md-1" for="pass">Password:</label><br>
                        <input class="offset-md-1" type="password" id="pass" name="password">
                    
                        <button class="btn btn-success btn-sm" type="submit">Login</button>
                    </form>
                </div>
            </div>    
        </div>
    </div>
</div>





{% endblock %}

mysite/users/templates/users/logout.html
{% extends  'food/base.html' %}

{% block body %}
<form method="POST">
     {% csrf_token %}
     <h3>Are you sure you want to logout</h3>
     <button type="Submit">Confirm</button>


{% endblock  %} 

mysite/users/templates/users/orders.html
{% extends 'food/base.html' %}

{% block body %}

<form method="POST">
    {% csrf_token %}
    <p>
        Are you sure you want to confirm the order for <b>product {{ pdcd }}</b> by <b>{{ user }}</b>
    </p>

    <label for='qty'>Enter Quantity: </label><br>
    <input id='qty' name='qty' type='number' value='1'>

    <button class="btn btn-danger btn-sm" type="Submit">
        Confirm
    </button>
</from>


{% endblock %}

mysite/users/templates/users/orders_upd.html
{% extends 'food/base.html' %}

{% block body %}

<br><br><br>

<div class="container">
    <div class="row">
         <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Update Orders
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                    
                       <br><label>Quantity: </label><br>
                       {{ form.quantity }}

                       
                        <button class="btn btn-danger btn-sm" type="submit">Confirm</button>
                    </form>
                </div>
            </div>    
        </div>
    </div>
</div>





{% endblock %}

mysite/users/templates/users/payment.html
{% extends 'food/base.html' %}

{% block body %}

<br><br><br>

<h3>
    Pay ${{tot }}
</h3>

<div id="paypal-button-container">

</div>

<script>
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var totamt = "{{ tot }}";
    var url = "{% url 'users:oa' %}";
    var csrftoken = getCookie('csrftoken');
    var redirect_url = "{% url 'users:ps' %}";

    // Render the PayPal button into #paypal-button-container
    paypal.Buttons({

        style: {
            color:  'blue',
            shape:  'pill',
            label:  'pay',
            height: 40,
        },

        // Call your server to set up the transaction
        createOrder: function(data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: totamt
                    }
                }]
            });
        },

        // Call your server to finalize the transaction
        onApprove: function(data, actions) {
            return actions.order.capture().then(function(details) {
                console.log(details);
                SendData();
                //alert('Transaction completed by ' + details.payer.name.given_name + '!');
                function SendData() {
                    // url : gives the path to where our data goes
                    fetch(url, {
                        method: "POST",
                        headers: {
                            "Content-type": "application/json",
                            "X-CSRFToken": csrftoken,
                        },
                        body: JSON.stringify({
                            orderID: 10,
                            transID: details.id,
                            payment_method: 'Test',
                            status: details.status,
                        }),
                    })
                    .then((response) => response.json())
                    //.then(data => console.log(data));
                    .then((data) => {
                        window.location.href = redirect_url;
                    });
                }
            });
        }
    }).render('#paypal-button-container');
</script>

{% endblock %}

mysite/users/templates/users/profile.html
{% extends 'food/base.html' %}

{% block body %}
<br><br><br>

<div class="container">
    <div class="row">
         <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Profile
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                       
                        <div>
                            <img style="margin-bottom: 15px;" height="100px" width="100px" src="{{ user.profile.image.url }}">
                        </div>

                        <div style="margin-top: 20px"class="offset-md-1">
                            <span>{{ user.first_name }}</span>
                            <span>{{ user.last_name }}</span><br>
                            <span>{{ user.email }}</span>
                            <p>{{ user.profile.location}}</p>
                        </div>

                    </div>
                    
                </div>
            </div>    
        </div>
    </div>
</div>




{% endblock %}

mysite/users/templates/users/pymtsuccess.html
{% extends 'food/base.html' %}

{% block body %}

<h1>This is the payment success page</h1>

<a href="{% url 'food:index' %}" class="btn btn-dark">
    Back to Home
</a>

{% endblock %}

mysite/users/templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}

<br><br><br>

<div class="container">
    <div class="row">
         <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}

                        <label class="offset-md-1">Username: </label><br>
                        <span class="offset-md-1">{{ form.username }}</span>

                        <br><label class="offset-md-1">Email: </label><br>
                        <span class="offset-md-1">{{ form.email }}</span>

                        <br><label class="offset-md-1">First Name: </label><br>
                        <span class="offset-md-1">{{ form.first_name }}</span>

                        <br><label class="offset-md-1">Last Name: </label><br>
                        <span class="offset-md-1">{{ form.last_name }}</span>

                        <br><label class="offset-md-1">Password: </label><br>
                        <span class="offset-md-1">{{ form.password1 }}</span>

                        <br><label class="offset-md-1">Confirm Password: </label><br>
                        <span class="offset-md-1"> {{ form.password2 }}</span>



                        
                        <button class="btn btn-success btn-sm "type='submit'>Sign Up</button>
                    </form>
                </div>
            </div>    
        </div>
    </div>
</div>


{% endblock %}